/*
 * US_Sensor.h
 *
 *  Created on: Oct 11, 2024
 *      Author: amr mohamed
 */

#ifndef ECUAL_US_SENSOR_H_
#define ECUAL_US_SENSOR_H_

#include "std_types.h"
#include "gpio.h"
/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define US_ECHO_PORT  PORTD_ID
#define US_TRIG_PORT  PORTD_ID
#define US_ECHO_PIN   PIN6_ID
#define US_TRIG_PIN   PIN7_ID
/*******************************************************************************
 *                            Function declarations                            *
 *******************************************************************************/

/*
 * Initializes the ultrasonic sensor.
 * This function sets up the necessary configurations for the ultrasonic sensor.
 */
void Ultrasonic_init(void);

/*
 * Triggers the ultrasonic sensor to send a pulse.
 * This function sends a trigger pulse to the ultrasonic sensor to start a measurement.
 */
void Ultrasonic_Trigger(void);

/*
 * Reads the distance measured by the ultrasonic sensor.
 * return The distance measured by the ultrasonic sensor in centimeters.
 * This function reads the echo pulse duration and calculates the distance based on the speed of sound.
 */
uint16 Ultrasonic_readDistance(void);

/*
 *  his is the callback function called by the ICU driver.
 *  It calculates the high time (pulse time) generated by the ultrasonic sensor.
*/
void Ultrasonic_edgeProcessing(void);
#endif /* ECUAL_US_SENSOR_H_ */
